# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURIZED_DATA: features
  FEATURIZED_TRAIN_DATA: train.pkl
  FEATURIZED_TEST_DATA: test.pkl
  MODEL_DIR: model
  MODEL_NAME: model.pkl

source_data_url: https://drive.google.com/file/d/1nqlr1tP4uHp-LVO6mIhwQOKRCJEhqk6r/view?usp=sharing
source_download_dir:
  data_dir: data
  data_file: data.xml
local_data_dirs:
  - path_to_local_data_1
  - path_to_local_data_2
