# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_base_model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks

source_data_url: https://drive.google.com/file/d/1nqlr1tP4uHp-LVO6mIhwQOKRCJEhqk6r/view?usp=sharing
source_download_dirs:
  data_dir: data
  data_file: data.xml
local_data_dirs:
  - path_to_local_data_1
  - path_to_local_data_2
